In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("FullAvatarDescriptions.xlsx")
df

,AvatarId,Description,Emotions
0,avatar_female_0,She has brown curly hair. Her eyebrows and eye...,she is look good
1,avatar_female_0,Her hair is very long and brown colored. Her e...,"sexy,stylish,rich lady,awesome"
2,avatar_female_0,she has thick brown medium cut hair with saw b...,excited and mentally powerful
3,avatar_female_0,She has dark brown stylish short hairs. Her sk...,very good matched nice dressed look
4,avatar_female_0,"She has brown, smooth punk hair. She has small...","stylish,calm girl."
...,...,...,...
2391,avatar_male_49,he has half head hair. he has short dark eyebr...,he stand like photo pose. he is happy.
2392,avatar_male_49,"he is bald on top, red hair on sides. his eyeb...",strange weird akward
2393,avatar_male_49,He is bald headed person having some hair near...,looks like a funny comic person
2394,avatar_male_49,This man has fully bald head. But at the backs...,Think past all incidents previously happened a...
2395,avatar_male_49,He has partially balded head with hair on the ...,"cool, casual and handsome"

In [3]:
newDf = df[['AvatarId','Description']]
newDf

             AvatarId                                        Description
0     avatar_female_0  She has brown curly hair. Her eyebrows and eye...
1     avatar_female_0  Her hair is very long and brown colored. Her e...
2     avatar_female_0  she has thick brown medium cut hair with saw b...
3     avatar_female_0  She has dark brown stylish short hairs. Her sk...
4     avatar_female_0  She has brown, smooth punk hair. She has small...
...               ...                                                ...
2391   avatar_male_49  he has half head hair. he has short dark eyebr...
2392   avatar_male_49  he is bald on top, red hair on sides. his eyeb...
2393   avatar_male_49  He is bald headed person having some hair near...
2394   avatar_male_49  This man has fully bald head. But at the backs...
2395   avatar_male_49  He has partially balded head with hair on the ...

[2396 rows x 2 columns]

In [7]:
newDf.to_excel("dataset.xlsx",encoding = "UTF-8")

In [9]:
newDf

             AvatarId                                        Description
0     avatar_female_0  She has brown curly hair. Her eyebrows and eye...
1     avatar_female_0  Her hair is very long and brown colored. Her e...
2     avatar_female_0  she has thick brown medium cut hair with saw b...
3     avatar_female_0  She has dark brown stylish short hairs. Her sk...
4     avatar_female_0  She has brown, smooth punk hair. She has small...
...               ...                                                ...
2391   avatar_male_49  he has half head hair. he has short dark eyebr...
2392   avatar_male_49  he is bald on top, red hair on sides. his eyeb...
2393   avatar_male_49  He is bald headed person having some hair near...
2394   avatar_male_49  This man has fully bald head. But at the backs...
2395   avatar_male_49  He has partially balded head with hair on the ...

[2396 rows x 2 columns]

In [23]:
removeIndices = []
for i in df.index:
    avatarId = df.loc[i]['AvatarId']
    #print(f"{type(avatarId)},{avatarId}")
    #print(f"{len(avatarId)},{avatarId[0:7]}\n")
    if type(avatarId) != str or len(avatarId) < 6 or avatarId[0:6] != "avatar":
        removeIndices.append(i)
print(len(removeIndices))
newDf2 = newDf.drop(removeIndices)
newDf2

395

             AvatarId                                        Description
0     avatar_female_0  She has brown curly hair. Her eyebrows and eye...
1     avatar_female_0  Her hair is very long and brown colored. Her e...
2     avatar_female_0  she has thick brown medium cut hair with saw b...
3     avatar_female_0  She has dark brown stylish short hairs. Her sk...
4     avatar_female_0  She has brown, smooth punk hair. She has small...
...               ...                                                ...
2391   avatar_male_49  he has half head hair. he has short dark eyebr...
2392   avatar_male_49  he is bald on top, red hair on sides. his eyeb...
2393   avatar_male_49  He is bald headed person having some hair near...
2394   avatar_male_49  This man has fully bald head. But at the backs...
2395   avatar_male_49  He has partially balded head with hair on the ...

[2001 rows x 2 columns]

In [24]:
newDf2.to_excel("final_dataset.xlsx")